#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u 'fenchelfen' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"

git init

git remote add origin "https://github.com/fenchelfen/$repo_name.git"
